### ISSUE TITLE
Error al iniciar el launcher de minecraft

### ISSUE THREAD

**Issue by Requiem8525** [HeberonYT/MultiMinecraft#80]
Buenas tardes,

Después de crear una instancia le doy click al botón PLAY, esto me abre la ventana del launcher pero se queda congelado en la parte de carga de perfiles y no me permite iniciar ni realizar alguna acción. Probé cambiando el launcher pero me sale el mismo error en todos. Agradecería cualquier ayuda que puedan darme.

![image](https://user-images.githubusercontent.com/73917611/98055376-571e2900-1e0b-11eb-9dc8-4c8024710c04.png)

Esta es la información de la instancia creada:

![image](https://user-images.githubusercontent.com/73917611/98055607-e1668d00-1e0b-11eb-9b93-2e45c99736ab.png)

![image](https://user-images.githubusercontent.com/73917611/98055564-be3bdd80-1e0b-11eb-88c2-6a909ce8bfa2.png)

La consola me muestra lo siguiente:

[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: cs Cesky (cs)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: de Deutsch (de)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: en English (en)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: es Español (es)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: et Estonian (et)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: fi Finnisch (fi)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: fr Français (fr)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: hr Hrvatski (hr)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: hu Magyar (hu)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: it Italiano (it)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: kx Shiginima (kx)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: pl Polszczyzna (pl)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: pt Português (pt-br)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: ru Русский (ru)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: tl Tagalog (tl)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: tr Türkçe (tr)
[19:18:25 INFO]: [Shiginima Launcher Log] SUCCESSFULLY LOADED LANGUAGE: vi Vietnamese (vi)
[19:18:26 INFO]: [ShiginimaLauncher] options.txt not found. Run minecraft at least once to generate the file!.
[19:18:26 INFO]: Minecraft Launcher Shiginima Launcher v4.400 (through bootstrap 100) started on windows...
[19:18:26 INFO]: Current time is Nov 3, 2020 7:18:26 PM
[19:18:26 INFO]: System.getProperty('os.name') == 'Windows 10'
[19:18:26 INFO]: System.getProperty('os.version') == '10.0'
[19:18:26 INFO]: System.getProperty('os.arch') == 'amd64'
[19:18:26 INFO]: System.getProperty('java.version') == '1.8.0_271'
[19:18:26 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[19:18:26 INFO]: System.getProperty('sun.arch.data.model') == '64'
[19:18:26 INFO]: proxy == DIRECT
[19:18:26 INFO]: Refreshing local version list...
[19:18:26 INFO]: Refreshing remote version list...
[19:18:27 INFO]: Refresh complete.
[19:18:27 ERROR]: Unexpected exception refreshing profile list
java.lang.NullPointerException
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:252) [KeiNett.exe:v1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_271]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_271]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[19:18:27 INFO]: Starting ensureloggedin
[19:18:27 ERROR]: Unhandled exception in executor com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask@496183a
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_271]
	at com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask.done(ExceptionalThreadPoolExecutor.java:81) [KeiNett.exe:v1.0]
	at java.util.concurrent.FutureTask.finishCompletion(Unknown Source) [?:1.8.0_271]
	at java.util.concurrent.FutureTask.setException(Unknown Source) [?:1.8.0_271]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_271]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NullPointerException
	at net.minecraft.launcher.profile.ProfileManager.saveProfiles(ProfileManager.java:72) ~[KeiNett.exe:v1.0]
	at net.minecraft.launcher.SwingUserInterface.showLoginPrompt(SwingUserInterface.java:223) ~[KeiNett.exe:v1.0]
	at net.minecraft.launcher.Launcher.ensureLoggedIn(Launcher.java:304) ~[KeiNett.exe:v1.0]
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:257) ~[KeiNett.exe:v1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_271]
	... 4 more
[19:18:37 FATAL]: Unhandled exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException
	at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel.populateProfiles(ProfileSelectionPanel.java:102) ~[KeiNett.exe:v1.0]
	at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel$1.run(ProfileSelectionPanel.java:95) ~[KeiNett.exe:v1.0]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:1.8.0_271]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:1.8.0_271]
	at java.awt.EventQueue.access$500(Unknown Source) ~[?:1.8.0_271]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_271]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_271]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_271]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_271]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:1.8.0_271]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_271]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_271]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_271]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_271]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_271]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_271]

**Comment by HeberonYT** [comment]
Hola , cambia de lanzador, los perfiles no se muestran porque fueron creados con un lanzador superior.
Otra opción es borrar el archivo "launcher_profiles.json" que está dentro de la carpeta .minecraft, eso significa que deberás crear un perfil nuevo.
